function esc(value: string | null | undefined): string {
  return (value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function linesBlock(lines: string[], startY: number, lineHeight = 28): string {
  return lines.map((line, index) => `<text x="70" y="${startY + index * lineHeight}" font-size="20" fill="#222" font-family="'Segoe UI', sans-serif">${esc(line)}</text>`).join("");
}

export function renderMfcSvg(input: Record<string, unknown>): string {
  const applicant = [
    `Name: ${String(input.applicantName ?? "")}`,
    `Sex: ${String(input.sex ?? "")}`,
    `DOB: ${String(input.dateOfBirth ?? "")}`,
    `CID: ${String(input.cid ?? "")}`,
    `Number: ${String(input.number ?? "")}`,
    `Weight: ${String(input.weight ?? "")}`,
    `MFC Reason: ${String(input.mfcReason ?? "")}`,
    `Date: ${String(input.examDateText ?? "")}`,
  ];
  const reports = [
    `Blood Test: ${String(input.bloodTest ?? "")} ${String(input.bloodResult ?? "")}`.trim(),
    `MRI Test: ${String(input.mriTest ?? "")} ${String(input.mriResult ?? "")}`.trim(),
    `Eye Test: ${String(input.eyeTest ?? "")} ${String(input.eyeResult ?? "")}`.trim(),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="1900" viewBox="0 0 1400 1900">
  <rect width="1400" height="1900" fill="#f7f3ea"/>
  <rect x="40" y="40" width="1320" height="1820" rx="28" fill="#fffdf8" stroke="#111827" stroke-width="4"/>
  <text x="700" y="120" text-anchor="middle" font-size="46" font-weight="700" fill="#0f172a" font-family="'Segoe UI', sans-serif">MOUNT ZONAH</text>
  <text x="700" y="175" text-anchor="middle" font-size="34" font-weight="700" fill="#0f172a" font-family="'Segoe UI', sans-serif">MEDICAL FITNESS CERTIFICATE</text>
  <text x="70" y="245" font-size="28" font-weight="700" fill="#0f172a" font-family="'Segoe UI', sans-serif">Applicant Information</text>
  ${linesBlock(applicant, 300, 42)}
  <text x="70" y="700" font-size="28" font-weight="700" fill="#0f172a" font-family="'Segoe UI', sans-serif">Test Reports</text>
  ${linesBlock(reports, 755, 48)}
  <text x="70" y="1080" font-size="28" font-weight="700" fill="#0f172a" font-family="'Segoe UI', sans-serif">Final Summary</text>
  ${linesBlock([String(input.finalSummary ?? "No summary provided.")], 1135, 42)}
  <text x="70" y="1600" font-size="24" fill="#0f172a" font-family="'Segoe UI', sans-serif">Medical Officer: ${esc(String(input.officerName ?? ""))}</text>
  <text x="70" y="1650" font-size="24" fill="#0f172a" font-family="'Segoe UI', sans-serif">Signature: ${esc(String(input.officerSignature ?? ""))}</text>
  <text x="70" y="1810" font-size="18" fill="#475569" font-family="'Segoe UI', sans-serif">Generated by Legacy BD EMS Doctor Portal</text>
</svg>`;
}

export function renderPrescriptionSvg(input: Record<string, unknown>, medicineLines: string[]): string {
  const details = [
    `Patient: ${String(input.patientName ?? "")}`,
    `CID: ${String(input.cid ?? "")}`,
    `Age: ${String(input.age ?? "")}`,
    `Sex: ${String(input.sex ?? "")}`,
    `Weight: ${String(input.weight ?? "")}`,
    `Date: ${String(input.prescriptionDateText ?? "")}`,
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="1900" viewBox="0 0 1400 1900">
  <rect width="1400" height="1900" fill="#faf8f3"/>
  <rect width="1400" height="1900" fill="url(#paperLines)" opacity="0.92"/>
  <defs>
    <pattern id="paperLines" width="1400" height="40" patternUnits="userSpaceOnUse">
      <rect width="1400" height="40" fill="#fdfcf9"/>
      <line x1="0" y1="39" x2="1400" y2="39" stroke="#5aa8ff" stroke-width="1.2" opacity="0.55"/>
      <line x1="96" y1="0" x2="96" y2="1900" stroke="#ff5f86" stroke-width="2" opacity="0.55"/>
    </pattern>
  </defs>
  <text x="700" y="110" text-anchor="middle" font-size="44" font-weight="700" fill="#111827" font-family="'Comic Sans MS', 'Segoe Print', cursive">~MOUNT ZONAH MEDICAL HOSPITAL~</text>
  ${linesBlock(details, 190, 44)}
  <text x="120" y="520" font-size="24" font-weight="700" fill="#111827" font-family="'Segoe Print', cursive">Hx / Findings:</text>
  ${linesBlock([String(input.symptoms ?? ""), String(input.findings ?? "")], 560, 38)}
  <text x="120" y="760" font-size="24" font-weight="700" fill="#111827" font-family="'Segoe Print', cursive">Rx:</text>
  ${linesBlock(medicineLines, 810, 38)}
  <text x="120" y="1200" font-size="24" font-weight="700" fill="#111827" font-family="'Segoe Print', cursive">Advice:</text>
  ${linesBlock([String(input.advice ?? ""), String(input.followUp ?? "")], 1240, 38)}
  <text x="900" y="1740" font-size="24" fill="#111827" font-family="'Segoe Print', cursive">Dr. Signature: ${esc(String(input.signatureText ?? ""))}</text>
</svg>`;
}

export function renderMedicalRecordSvg(input: Record<string, unknown>): string {
  const lines = [
    `Name: ${String(input.patientName ?? "")}`,
    `CID: ${String(input.cid ?? "")}`,
    `Phone Number: ${String(input.phone ?? "")}`,
    `Details of injury: ${String(input.injuryDetails ?? "")}`,
    `Treatment Details: ${String(input.treatmentDetails ?? "")}`,
    `Date: ${String(input.recordDateText ?? "")}`,
    `Done By: ${String(input.doneByText ?? "")}`,
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="1600" viewBox="0 0 1400 1600">
  <rect width="1400" height="1600" fill="#101720"/>
  <rect x="60" y="60" width="1280" height="1480" rx="24" fill="#1a1208" opacity="0.98"/>
  <text x="120" y="150" font-size="42" fill="#f8fafc" font-weight="700" font-family="'Segoe UI', sans-serif">Medical Record History</text>
  ${linesBlock(lines, 250, 60)}
</svg>`;
}
